version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 10
  build:
    commands:
      - echo Building the Node code...
      - cd $CODEBUILD_SRC_DIR/nodejs-todo
      - npm run test
artifacts:
  secondary-artifacts:
    nodejs_artifacts:
      base-directory: nodejs-app
      files:
        - index.js
        - package.json
